---
pivotal_token:   <%= ENV['PIVOTAL_TOKEN'] %>
pivotal_project: 1254912
pivotal_reference_prefix: pivotal
deploy_tag_prefix: production_deploy_
semaphore_auth_token: <%= ENV['SEMAPHORE_AUTH_TOKEN'] %>
semaphore_project_url: https://betterplace.semaphoreci.com/projects/betterplace
